In [ ]:
!pip install pandas gseapy pykegg biopython igraph plotnine

In [ ]:
# Importing the csv file for young surviving mice (Created in R)
import pandas as pd

res = pd.read_csv("res_young_surv_df.csv", index_col=0)
res.head()

In [ ]:
# Filtering significant genes
sig = res[
    (res["padj"] < 0.05) &
    (abs(res["log2FoldChange"]) > 1)
]

sig_genes = sig.index.tolist()
sig_genes = [g.split(".")[0] for g in sig_genes]  # Ensembl-Versionen entfernen
sig_genes[:10]

In [ ]:
# Applying KEGG analysis
!pip install gseapy mygene

import gseapy as gp

enr = gp.enrichr(
    gene_list=sig_genes,
    gene_sets="KEGG_2019_Mouse",
    cutoff=0.05
)

enr.results.head()

In [5]:
# Filtering pathways for keywords 
kegg = enr.results  # aus gseapy
kegg[kegg['Term'].str.contains("FoxO|proteasome|ubiquitin|cardiac|circadian rhythm|notch signaling|inositol phosphate metabolism", case=False)]

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
90,KEGG_2019_Mouse,FoxO signaling pathway,10/132,0.167540,0.487727,0,0,1.458737,2.606082,IL10;CCNB1;IL6;BCL2L11;GADD45B;BCL6;TNFSF10;IR...
138,KEGG_2019_Mouse,Cardiac muscle contraction,5/78,0.403509,0.758386,0,0,1.216366,1.103921,RYR2;COX4I2;COX7B2;MYH6;MYH7
215,KEGG_2019_Mouse,Circadian rhythm,1/30,0.807180,0.992395,0,0,0.611503,0.130989,ARNTL
242,KEGG_2019_Mouse,Notch signaling pathway,1/49,0.932103,0.999994,0,0,0.369078,0.025951,DTX3L
254,KEGG_2019_Mouse,Ubiquitin mediated proteolysis,3/138,0.980203,0.999994,0,0,0.392607,0.007850,SOCS1;PML;DDB2
256,KEGG_2019_Mouse,Inositol phosphate metabolism,1/73,0.981859,0.999994,0,0,0.245740,0.004499,PIK3C2G

In [ ]:
# Importing the csv file for old mice (Created in R)

import pandas as pd

res = pd.read_csv("res_age_df.csv", index_col=0)
res.head()

In [ ]:
# Filtering significant genes
sig = res[
    (res["padj"] < 0.05) &
    (abs(res["log2FoldChange"]) > 1)
]

sig_genes = sig.index.tolist()
sig_genes = [g.split(".")[0] for g in sig_genes]  # Ensembl-Versionen entfernen
sig_genes[:10]

In [8]:
# Filtering pathways for keywords 
kegg = enr.results  # aus gseapy
kegg[kegg['Term'].str.contains("FoxO|proteasome|ubiquitin|cardiac|circadian rhythm|notch signaling|inositol phosphate metabolism", case=False)]

,Gene_set,Term,Overlap,P-value,Adjusted P-value,Old P-value,Old Adjusted P-value,Odds Ratio,Combined Score,Genes
90,KEGG_2019_Mouse,FoxO signaling pathway,10/132,0.167540,0.487727,0,0,1.458737,2.606082,IL10;CCNB1;IL6;BCL2L11;GADD45B;BCL6;TNFSF10;IR...
138,KEGG_2019_Mouse,Cardiac muscle contraction,5/78,0.403509,0.758386,0,0,1.216366,1.103921,RYR2;COX4I2;COX7B2;MYH6;MYH7
215,KEGG_2019_Mouse,Circadian rhythm,1/30,0.807180,0.992395,0,0,0.611503,0.130989,ARNTL
242,KEGG_2019_Mouse,Notch signaling pathway,1/49,0.932103,0.999994,0,0,0.369078,0.025951,DTX3L
254,KEGG_2019_Mouse,Ubiquitin mediated proteolysis,3/138,0.980203,0.999994,0,0,0.392607,0.007850,SOCS1;PML;DDB2
256,KEGG_2019_Mouse,Inositol phosphate metabolism,1/73,0.981859,0.999994,0,0,0.245740,0.004499,PIK3C2G